
import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "SimpleFullscreen"
decorations = "None"
padding = { x = 20, y = 20 }
opacity = 0.8
blur = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 14

[mouse]
hide_when_typing = true
