
import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

[env]
# TERM = "xterm-256color"
# TERM = "screen-256color"
TERM = "tmux-256color"

[window]
startup_mode = "SimpleFullscreen"
# startup_mode = "Windowed"
decorations = "Full"
padding = { x = 20, y = 20 }
# opacity = 0.8
opacity = 1
blur = true
option_as_alt = "OnlyLeft" # (macos only)

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 16

[mouse]
hide_when_typing = true
